### ISSUE TITLE
core: SSL server

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/cb-client-wallet#10]
Re-enable SSL by default (was defaulted to TCP in #1 )
Test wallet on SSL servers

**Comment by tomt1664** [comment]
The alternative to this is to have the wallet check the federation signatures - this would allow anyone (untrusted) to run an electrum server.

**Comment by nkostoulas** [comment]
To do when we move to SSL server
https://github.com/commerceblock/guardnode-wallet/commit/b1c136bc473512d89dfc2a998399a057308f8331
