### ISSUE TITLE
KYC File Creation

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/cb-client-wallet#24]
When kycfile.dat is exported, if a kyc.dat file already exists there is no message to warn and the file is not overwritten.

Need to overwrite file automatically or prompt?

**Comment by lawlawlaw** [comment]
I was unable to reproduce the error on my system.

**Comment by cryptopoly** [comment]
That's totally ruined my party :P I'll get you next time gadget!!!

**Comment by lawlawlaw** [comment]
Issue still present on some systems - need to confirm file overwrite.

**Comment by cryptopoly** [comment]
Likely to du mac nuance with file modification stamps
