### ISSUE TITLE
Default contract

### ISSUE THREAD

**Issue by tomt1664** [commerceblock/cb-client-wallet#38]
Separately downloading the contract file and copying it to the .cbwallet directory seems a bit of a painful UX. One possibility is to include the initial contract as a default in the release, which is written to the directory on first startup if it is not there already.

**Comment by nkostoulas** [comment]
Agreed. I think when running from cmd it makes sense but when distributing the binary is not good. We could amend the following:
```
if not config.get('contract_hash'):
        print_stderr("Contract Hash not set. Move the `contract` file to `{}`".format(config.electrum_path()))
        sys.exit(1)
```
so that it sets it from the file directly. We'll need to see how to include a file in the binary so that run_electrum knows where to read it from.

**Comment by nkostoulas** [comment]
Possibly in a similar way icons are handled.
