### ISSUE TITLE
core: Electrum wallet hangs

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/cb-client-wallet#58]
Wallet seems to hang frequently

**Comment by cryptopoly** [comment]
Batched transactions also tend to lock up python (bulk payments as below). Will do more testing on lower resources to see the impact (currently on latest i9!)

2dZaat2vMPeYJFKW3Xzz4Czvn4ERTDoejmu,   400
2dZdhMcYuHRZinmH6QUAmuHFDCk7qtPvZwD, 400
2daAwt9UpWrMkhz9TecigJ5m3TiNqibyx8V, 400
2dkXSRcShq1TRgku5K8SXxrRKkJAB9fvJd2, 400
2dc1vr9rzQdKax8wZtwePvemye6G1qyCm8a, 400
2du8VcNVKYnwNZitYe7AjbGyYaVa5vYwzdL, 400
2dwLoBuTAXHqL17P2wTTCgmJfnQSZwUR51p, 400
2dZcuYPirP21qjCVusP1h87CsYbHra9pErs, 400
2dtPoVHkpz5GcSNR9PWHhcyrZPV2K3ksDUR, 400
2di6rSb5UCbE1WkLW1tm6CKApTkbm5LSDdd, 400
2di7htXqNWZmgTs6hDGp5zXYmeX2o1XNHxc, 400
2dgE3a9JzfaPaAuvswYgn4ZaQWVmK5BB7tC, 400
2dwPcJR6DGfg9oyBGYw4ZkReF26Lyo7SxwD, 400
2dn2j4tmp46oEDfYSTb9GsS5LvBckL5Yk16, 400
2dubJ9GAiLZ6fUqrBH6BAev74yEfW5dXnMJ, 400
2ddV9PsiYaZoakqSj5KM7YyDGa5z4EEkRbW, 400
2djLg8AzYoox8oYdmjJhrQyNAeHHiNCZepx, 400
2doh7NV7p9B3rghsyFiKAZrwgqaeW1Qg2KJ, 400
2daMkwXE1jwUjh5jVWyNKx9buZvDxciS1HA, 400
2dvqHcQCkRDJxqJ4FL8XvwXrrCvZLiN5CoR, 400
2dr5cc7CwHHn3UxTpDnnHFyBCZg9Kw6zt1k, 400
2dwnRSNVw18p13vnh7gMGNahPp9J8qgqAba, 400
2dsGH2FRRQVwtrf7cR4AuDGnJtE3rSDDWTt, 400
2degmKpjEJRZE5ufC3Uv4uypd6th3Mj8BSB, 400
2dxd5RcirSAuNEYLYsRtCzCBNr2fxnM9oi6, 400
2do8d2kkj8HPVi2ZsmSifNZJGr3EzEbvo8T, 400
2dtg45wnrAYVSDFLeLBj7zNmcuPzpGT5Z8r, 400
2dfUFNcSkx9SZe1SGmjap419BjkMHiLM49S, 400
2dskhCTg6ebxuHWuvTfnuf8UsUPgDNdbrLX, 400
2dmQMQ6rhMmFSnZbt4s93XoDvHfhTtiM4Js, 400
2dircTo3jkb4FmEesMKdikAKwqSQN3TSizz, 400
2doW7YQ8oecR2VmB5oNyBZGegp7WwM19VJh, 400
2daKn9ykjt3bP9HJqg4S6z6AzMXPsmyGffx, 400
2dsBSyGhWA6ygBcyM53r5ZiXaizWwRQjRL4, 400
2dhcPz54wpGxV56jEWu3W4ZqWLS4A7HehAF, 400
2dkFjBZmLLYcVEs2aSiG3xd7WfKLULd4Bxb, 400
2dwiJdqyuWevmZDjwgzfQGg7nwS7yCNng6j, 400
2dkCaCadN6cv3YcboBs1EhHkjHuYwkpzkUN, 400
2dgFPHroGxNki9vMBY6kin32wGfkFmNABw8, 400
2dw9nJyv6hMFRoWvTE3Vmpvy3XHZCe4xwNY, 400
2dmeXzEabV2SQxG1Xp8LLdeQuE3QJoPoJ4c, 400
2daU4Jr5nTAVu4gedq9ogioY8KRb5EbaNKp, 400
2ddq2A1u63Zht6imJSQAM178BYhLpVff3C7, 400
2dg4a1YuFBfy7wXbdPWZHpA6cTc83gLTJsP, 400
2dnYph2bEDphUxXQG9TTAu5RCFtA5vrpuoD, 400
2dbAvTffzq9yiUks9dEgnSS6WFXVyYLdyTv, 400
2dvn9NjWgWqPJyfW7fkgqtzFEKfFuWUhRpR, 400
2dsTBvJUFw9ac9c5zdvxVSSYxW79n62kRZW, 400
2dmnxtWhdoSSwAzpY1fNemTCisQ8Lofhz86, 400
2duEq3EC7eFXehVk7F4XKQKMjw2WjvSGbBo, 400
2drkvrCjQrJeuJuw13XFWNzxXfeRz8LfMyz, 400
2dspSe5PhNGSkM9CqN8L2kguw16ov7qrfEw, 400
2dagMWE24nZinwGQ87H3k4UxyTZ2iJj3Qrz, 400
2dehAPixDJd2KQ9M3Tzt4jmYrMzzP2AUHBx, 400
2dkGMfjmr4cZ6YnaarpDqsHqMZFfLYFdurw, 400
2dnhJ7d1tuicjoYSbiZV8RFnFYkgiw4QAyP, 400
2dhetQe2ptnRxJ6Le9p7MwKZtPTBjPPHmRh, 400
2drkrKJdC2uFQvLuqpqRwXyEHeRFNxCQsin, 400
2dcP4tacmWa7uL9vff9ZZrXzV5n8znwe7jn, 400
2da5qzQkhDKEKqD4GhpC7PEcnLKDE6nNjBy, 400
2dfyoDDwFmZPYtWJdXmfF3H2mkw9W5r5St9, 400
2dh65TaqemYjoJebWjQAcMr8jscwAyZANFL, 400
2dtEp1sgRfiUgdHU7ox2Sc2xJdhcGFHBJWz, 400
2dwHLkSJPwBq7fZx7JBZoix2vZAQjpikRAi, 400
2doeTZFyiSbwV4bTKyzfpaDyieHexHowQkA, 400
2duEC9YmQySjhgWD1641rM1L5VXPZh3D6jV, 400
2dtuVVkoq7cHYTqZ8ogcFx6qv32CN5Mg6N4, 400
2dtbu45mDET7RZH1EoQiBuRfCqQeYJbaqXz, 400
2di7zqXPtsECwzmtn4A81YBMbkYyfGbJhpK, 400
2dhMnHT5CCNFW57aVvnvRJDEvZaycKA1ccB, 400
2dmoemAwVkSWsNFJGvBT8vevw3apdYCQZor, 400
2dwhimTsSZScHaPJqXJ5sqrPjxo3MwKrc5J, 400
2dgnKjQeB8aH8Vxen2WPmZv9YvLepsSRufu, 400
2djZUCsqfPSgLyQze3oCsrUuTFCmvkpbmb5, 400
2dfjEEWEp9stAHQ8KkzYNoaQfwu8DxKjPy6, 400
2dcN1N4MBUVZqERrfWbjTJyRUi43dkhsQZD, 400
2do9Zj4Rhka73aZhmsyR6eXKbA5jzMF3h26, 400
2dn4DJn4Kdk7fKnsADsaPRTuPPLEwLrGWLR, 400
2dkRnr4fWgVRMcLHE4bL4Un7Jmhvuov5ZT3, 400
2dtxDZSEzwheLrvFKR4oziLMYgBsLXYGmpG, 400
2dnwjQTZzFYVrw4Fm6DMQBvHVZD4Ue4wZFM, 400
2dgUUa6cC4JLGbvxPFn1TdbMhbWY4Y2rZj5, 400
2do9v7jXpiD9X3eY167CUK3A9JvL6oJLHJb, 400
2dj13XotEaXrMaLvLyHjWznst5vVYSx6P3Q, 400
2djs3JzH4ag6U1HYue8Mz62Vu8ZWm1mVYYq, 400
2du6gACoite66TUEKKA8cTnUNKNwSg9swd1, 400
2dfnRHgcd7Y8MxGQbcM3ZcLYQMxJiS1nQe6, 400
2djJWGeqMmurdi4pb5Jcf5CQdhVX9pM7sMf, 400
2driXxVJrNXWPafv8SKHkFTeNQaHRAoVx72, 400
2doDdgChm9v7cw8smR3jhCRQR9DZfdJ3NVf, 400
2dwgknR7E7XtbuQX4gGh64V5WRYsdfmaCrY, 400
2dqXT2todaqoW6yvsPutCHEKS7JkeWdbRi5, 400
2dvUUaPZrBg8dWZx7wayNWPZkda2baFxkNo, 400
2dgmHKe3ep474D6bK9Kefbink8GnWzCDj2r, 400
2ddqAdE7MuSZx5WUNwbj6sVaKmRQ6Xzhbnp, 400
2dwRAx3qChNhNqiCe4hjukRhtrkoBjt718M, 400
2djBApiuV5PzfcrssBMLdYhESiJfaaix6Wj, 400
2dcRu1QQmkXJdCPaMPeatTk8Te3JCz7D7v7, 400
2dxBcWoingNGMq7DhmaX4PTBdWXi9BUQEYs, 400
2dm1WtJVnXzMsKfacueBHQn9xZsmPUkVikC, 400
2derrktpMmxCdaGPeFuKAQRun5cTqJDXgMA, 400
2dwu9BLiFGhLCHhs8uvmdNpZudQgRcxo5FA, 400
2djXdUhJ7c2rnmFRwdWX1LFe2BcBtBoQUX2, 400
2dkqW7MEE5JAN4QDUM3J7oV8qfzWy7vpAM1, 400
2doQXbLwhv8r563AXQZcsGZcn7Fn1Yv6gbC, 400
2ddUe6gwqz1LtMwTykDACMYtKWSNCe9JTzX, 400

**Comment by cryptopoly** [comment]
New error while importing public address for inflation fees (was also running three other wallets at the time). Wallet hung before error

<img width="906" alt="Screenshot 2019-07-15 at 13 10 31" src="https://user-images.githubusercontent.com/31970407/61215233-21c76680-a702-11e9-92ab-59b5cd460ece.png">

**Comment by cryptopoly** [comment]
One event causing wallet to hang is entering the send amount, possibly due to trying to retrieve price or fee information

**Comment by nkostoulas** [comment]
What's the issue here?

**Comment by cryptopoly** [comment]
Issue is that certain functions are making the wallet hang, especially if processing large tx's (e.g. sending to many addresses)

**Comment by nkostoulas** [comment]
Anything that is not covered by #79 ?

**Comment by cryptopoly** [comment]
No this was around the fees rather than huge volumes of transactions

**Comment by nkostoulas** [comment]
Ok all seems to stem from the same issue in #79
