### ISSUE TITLE
Send transaction fail

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/cb-client-wallet#61]
Sending a tx but electrum server ghosted me "Server did not answer".

In office with no drop in connection but shouldn't matter anyway as running local electrum server host

**Comment by cryptopoly** [comment]
<img width="843" alt="Screenshot 2019-07-15 at 13 28 46" src="https://user-images.githubusercontent.com/31970407/61216130-85529380-a704-11e9-8732-b2180658ba9e.png">

**Comment by nkostoulas** [comment]
This is not a client issue.

**Comment by cryptopoly** [comment]
Discussed with Tom also - will park some of these issues until staging environment ready...

**Comment by cryptopoly** [comment]
*because they're most likely local host environment related
