### ISSUE TITLE
whitelisting: Change address whitelisting

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/cb-client-wallet#71]
Turn off change addresses in preferences but when trying to send tx it failed on change address not whitelisted

**Comment by cryptopoly** [comment]
Images in slack... #cbclientwallet71

**Comment by nkostoulas** [comment]
This also looks like an issue in the Imported Wallet only. Will fix.

**Comment by nkostoulas** [comment]
Still you won't be able to use this as the imported wallet has no change addresses.
