### ISSUE TITLE
core: Absurdly high fee on sending inflation payments

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/cb-client-wallet#78]
Cannot spend inflation payments due to absurdly high fee (many inflation payments)

<img width="1083" alt="Screenshot 2019-07-29 at 18 06 43" src="https://user-images.githubusercontent.com/31970407/62120761-21120100-b2ba-11e9-8f5d-aa03503b2ffa.png">

**Comment by nkostoulas** [comment]
not a wallet issue
