### ISSUE TITLE
core: Sending tx with many outputs to sign times out due to 30 second broadcast limit

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/cb-client-wallet#83]
<img width="900" alt="Screenshot 2019-08-01 at 14 35 07" src="https://user-images.githubusercontent.com/31970407/62298654-51e56800-b46b-11e9-8a9e-57d1e4b31184.png">
<img width="1680" alt="Screenshot 2019-08-01 at 14 33 09" src="https://user-images.githubusercontent.com/31970407/62298655-51e56800-b46b-11e9-90b6-64e497c46860.png">

**Comment by nkostoulas** [comment]
@lawlawlaw increased this
