### ISSUE TITLE
Wallet crashing on load

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/cb-client-wallet#89]
Client wallet crashes on load.

Created with the following imported keys:
Tm33PuRKEjKhrGP6WBJNAz3yhNUt2AUzNmxMpPYH7uHymLyGd4Jd
ThC859tcKhMKWUZZEgna7oMDSjxLiZ85hisiYez8oLZxCqfF1jBB
TgaHuATvBNgzywX8Xu6QxXV7jveh1VpWvCer1x211PVrzSxQPJQJ

Error: attached

[wallet crash fail.txt](https://github.com/commerceblock/cb-client-wallet/files/3516226/wallet.crash.fail.txt)

**Comment by nkostoulas** [comment]
Can you attach the error from the command line?

**Comment by cryptopoly** [comment]
This might have been because of the massive tx's - have you seent the accompanying text file?

**Comment by nkostoulas** [comment]
Yes it's the Mac bug report, a bit hard to tell what's going on. I'll close this. Feel free to re-open if it happens again.
